global:
  # we query new data from the wall connector at the same interval
  scrape_interval: '10s'
  evaluation_interval: '10s'

scrape_configs:
  - job_name: 'teslawallconnector'
    metrics_path: /
    static_configs:
      - targets: ['connector:9225']
