{
 "title": "Tesla Wall Connector",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Charging station occupied?",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vehicle_connected" }
   ]
  },
  {
   "title": "Power Consumption (current charge)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "session_energy_wh / 1000" }
   ]
  },
  {
   "title": "Costs (current charge)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "session_energy_wh / 1000 * 0.3" }
   ]
  },
  {
   "title": "Duration (current charge)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "session_s" }
   ]
  },
  {
   "title": "Total Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uptime_all" }
   ]
  },
  {
   "title": "Total Power Consumption",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "energy_wh" }
   ]
  },
  {
   "title": "Grid Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "grid_v", "legendFormat": "Volt" }
   ]
  },
  {
   "title": "Grid Frequency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    { "expr": "grid_hz", "legendFormat": "Hz" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "pcba_temp_c", "legendFormat": "PCB" },
    { "expr": "handle_temp_c", "legendFormat": "Handle" },
    { "expr": "mcu_temp_c", "legendFormat": "MCU" }
   ]
  },
  {
   "title": "Ampere",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "vehicle_current_a", "legendFormat": "Vehicle Current" }
   ]
  },
  {
   "title": "Watt",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "(currentA_a + currentB_a + currentC_a) * grid_v",
     "legendFormat": "Vehicle Power"
    }
   ]
  },
  {
   "title": "WiFi Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "wifi_signal_strength", "legendFormat": "Signal" }
   ]
  }
 ]
}